export const sidebarData = [
  {
    parent: 'introduction',
    label: 'Java Introduction',
    children: [
      { label: 'Get Started With Java', link: '/docs/java/topics/Java-Introduction/Get-Started-With-Java' },
      { label: 'Your First Java Program', link: '/docs/java/topics/Java-Introduction/Your-First-Java-Program' },
      { label: 'Java Comments', link: '/docs/java/topics/Java-Introduction/Java-Comments' },
    ],
  },
  {
    parent: 'fundamentals',
    label: 'Java Fundamentals',
    children: [
      { label: 'Java variables and Literals', link: '/docs/java/topics/Java-Fundamentals/Java-variables-and-Literals' },
      { label: 'Java Data Types (Primitive)', link: '/docs/java/topics/Java-Fundamentals/Java-Data-Types' },
      { label: 'Java Operators', link: '/docs/java/topics/Java-Fundamentals/Java-Operators' },
      { label: 'Java Basic Input and OutPut', link: '/docs/java/topics/Java-Fundamentals/Java-Basic-Input-and-Output' },
      { label: 'Java Expressions,Statements ans Blocks', link: '/docs/java/topics/Java-Fundamentals/Java-Expressions' },
    ],
  },
  {
    parent: 'flow',
    label: 'Java Flow Control',
    children: [
      { label: 'Java if...else Statement', link: '/docs/java/topics/flow/Java-If-Else' },
      { label: 'Java switch Statement', link: '/docs/java/topics/flow/Java-Switch-Statement' },
      { label: 'Java for Loop', link: '/docs/java/topics/flow/Java-For-Loop' },
      { label: 'Java break Statement', link: '/docs/java/topics/flow/Java-Break-Statement' },
      { label: 'Java continue Statement', link: '/docs/java/topics/flow/Java-Continue-Statement' },
      { label: 'Java for-each Loop', link: '/docs/java/topics/flow/Java-For-Each-Loop' },
      { label: 'Java while and do...while Loop', link: '/docs/java/topics/flow/Java-While-Dowhile' },
      { label: 'Java Ternary Operator', link: '/docs/java/topics/flow/Java-Ternary' },
    ],
  },
  {
    parent: 'arrays',
    label: 'Java Arrays',
    children: [
      { label: 'Java Arrays', link: '/docs/java/topics/arrays/Java-Arrays' },
      { label: 'Java Multidimensional Arrays', link: '/docs/java/topics/arrays/Java-Multidimensional-Arrays' },
      { label: 'Java Copy Arrays', link: '/docs/java/topics/arrays/Java-Copy-Arrays' },
    ],
  },
  {
    parent: 'oop',
    label: 'Java OOP (I)',
    children: [
      { label: 'Java Classes & Objects', link: '/docs/java/topics/oop1/classes' },
      { label: 'Java Methods', link: '/docs/java/topics/oop1/Methods' },
      { label: 'Java Method Overloading', link: '/docs/java/topics/oop1/Methods-overloading' },
      { label: 'Java Constructors', link: '/docs/java/topics/oop1/constructors' },
      { label: 'Java Static Keyword', link: '/docs/java/topics/oop1/static-keyword' },
      { label: 'Java String', link: '/docs/java/topics/oop1/string' },
      { label: 'Java Access Modifiers', link: '/docs/java/topics/oop1/access-modifiers' },
      { label: 'Java this Keyword', link: '/docs/java/topics/oop1/this-keyword' },
      { label: 'Java final Keyword', link: '/docs/java/topics/oop1/final-keyword' },
      { label: 'Java Recursion', link: '/docs/java/topics/oop1/recursion' },
      { label: 'Java instance of Operator', link: '/docs/java/topics/oop1/instance-of-operator' },
    ],
  },
  {
    parent: 'oop2',
    label: 'Java OOP (II)',
    children: [
      { label: 'Java-Inheritance', link: '/docs/java/topics/oop2/inheritance' },
      { label: 'Java Method Overring', link: '/docs/java/topics/oop2/method-overriding' },
      { label: 'Java-Super', link: '/docs/java/topics/oop2/super' },
      { label: 'Java Abstraction', link: '/docs/java/topics/oop2/abstract-class-methods' },
      { label: 'Java Interface', link: '/docs/java/topics/oop2/interface' },
      { label: 'Java Polymorphism', link: '/docs/java/topics/oop2/polymorphism' },
      { label: 'Java Encapsulation', link: '/docs/java/topics/oop2/encapsulation' },
    ],
  },
  {
    parent: 'oop3',
    label: 'Java OOP (III)',
    children: [
      { label: 'Java Nested and Inner Class', link: '/docs/java/topics/oop3/nested-and-inner-class' },
      { label: 'Java Nested Static Class', link: '/docs/java/topics/oop3/nested-static-class' },
      { label: 'Java Anonymous Class', link: '/docs/java/topics/oop3/anonymous-class' },
      { label: 'Java Singleton Class', link: '/docs/java/topics/oop3/singleton-class' },
      { label: 'Java enums', link: '/docs/java/topics/oop3/enums' },
      { label: 'Java enum Constructor', link: '/docs/java/topics/oop3/enums-constructor' },
      { label: 'Java enum Strings', link: '/docs/java/topics/oop3/enum-String' },
      { label: 'Java Reflection', link: '/docs/java/topics/oop3/reflection' },
      { label: 'Java Package', link: '/docs/java/topics/oop3/package' },
    ],
  },
  {
    parent: 'Exception',
    label: 'Java Exception Handling',
    children: [
      { label: 'Java Exceptions', link: '/docs/java/topics/Exception/exceptions' },
      { label: 'Java Exception Handling', link: '/docs/java/topics/Exception/exceptions-handling' },
      { label: 'Java try...catch', link: '/docs/java/topics/Exception/try' },
      { label: 'Java throw and throws', link: '/docs/java/topics/Exception/throw' },
      { label: 'Java catch Multiple Exceptions', link: '/docs/java/topics/Exception/catch' },
      { label: 'Java try-with-resources', link: '/docs/java/topics/Exception/try-with-resources' },
      { label: 'Java Annotations', link: '/docs/java/topics/Exception/annotations' },
      { label: 'Java Annotation Types', link: '/docs/java/topics/Exception/annotation-types' },
      { label: 'Java Logging', link: '/docs/java/topics/Exception/logging' },
      { label: 'Java Assertions', link: '/docs/java/topics/Exception/assertions' },
    ],
  },
  {
    parent: 'List',
    label: 'Java List',
    children: [
      { label: 'Java Collections Framework', link: '/docs/java/topics/List/collection-framework' },
      { label: 'Java Collections Interface', link: '/docs/java/topics/List/collection-interface' },
      { label: 'Java List', link: '/docs/java/topics/List/list' },
      { label: 'Java ArrayList', link: '/docs/java/topics/List/arraylist' },
      { label: 'Java Vector', link: '/docs/java/topics/List/vector' },
      { label: 'Java Stack Class', link: '/docs/java/topics/List/stack-class' },
    ],
  },
  {
    parent: 'Queue',
    label: 'Java Queue',
    children: [
      { label: 'Java Queue Interface', link: '/docs/java/topics/Queue/interface' },
      { label: 'Java PriorityQueue', link: '/docs/java/topics/Queue/priorityqueue' },
      { label: 'Java Deque Interface', link: '/docs/java/topics/Queue/deque' },
      { label: 'Java LinkedList', link: '/docs/java/topics/Queue/linkedlist' },
      { label: 'Java ArrayDeque', link: '/docs/java/topics/Queue/arraydeque' },
      { label: 'Java BlockingQueue', link: '/docs/java/topics/Queue/blockingqueue' },
      { label: 'Java ArrayBlockingQueue', link: '/docs/java/topics/Queue/arrayblockingqueue' },
      { label: 'Java LinkedBlockingQueue', link: '/docs/java/topics/Queue/linkedblockingqueue' },
    ],
  },
    {
    parent: 'Map',
    label: 'Java Map',
    children: [
      { label: 'Java Map Interface', link: '/docs/java/topics/Map/map' },
      { label: 'Java HashMap', link: '/docs/java/topics/Map/hashmap' },
      { label: 'Java LinkedHashMap', link: '/docs/java/topics/Map/linkedhashmap' },
      { label: 'Java WeakHashMap', link: '/docs/java/topics/Map/weakhashmap' },
      { label: 'Java EnumMap', link: '/docs/java/topics/Map/enummap' },
      { label: 'Java SortedMap Interface', link: '/docs/java/topics/Map/sortedmap' },
      { label: 'Java NavigableMap Interface', link: '/docs/java/topics/Map/navigablemap' },
      { label: 'Java TreeMap', link: '/docs/java/topics/Map/treemap' },
      { label: 'Java ConcurrentMap Interface', link: '/docs/java/topics/Map/concurrentmap' },
      { label: 'Java ConcurrenctHashMap', link: '/docs/java/topics/Map/concurrenthashmap' },
    ],
  },
    {
    parent: 'Set',
    label: 'Java Set',
    children: [
      { label: 'Java Set Interface', link: '/docs/java/topics/Set/set' },
      { label: 'Java HashSet Class', link: '/docs/java/topics/Set/hashset' },
      { label: 'Java EnumSet', link: '/docs/java/topics/Set/enumset' },
      { label: 'Java LinkedHashSet', link: '/docs/java/topics/Set/linkedhashset' },
      { label: 'Java SortedSet Interface', link: '/docs/java/topics/Set/sortedset' },
      { label: 'Java NavigableSet Interface', link: '/docs/java/topics/Set/navigableset' },
      { label: 'Java TreeSet', link: '/docs/java/topics/Set/treeset' },
      { label: 'Java Algorithms', link: '/docs/java/topics/Set/algorithms' },
      { label: 'Java Iterator Interface', link: '/docs/java/topics/Set/iterator' },
      { label: 'Java Listlterator Interface', link: '/docs/java/topics/Set/listiterator' },
    ],
  },
];
